### ISSUE TITLE
Adding Issue, PR and Sadness contribution templates

### ISSUE THREAD

**Issue by Novalis15** [js-sadness/js-sadness.github.io#15]
The structure of the document-cookie sadness looks reasonable as a PR template:

* Title
* The Facts
* Why is this a Problem
* Suggestion to improve the language
* Workarounds
* Further reading

## TODO
- [x] New Sadness Template
- [x] Fix Sadness Template
- [x] Feature Request Template
- [x] Bug Report Template
